CREATE TABLE pending_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    raw_initial_text TEXT NOT NULL,
    draft_json TEXT NOT NULL,
    suggested_json TEXT,
    status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pending_draft_chat_id ON pending_draft (chat_id);

CREATE TABLE pending_selection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    candidates_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_pending_selection_chat_id ON pending_selection (chat_id);

CREATE TABLE dedupe_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    dedupe_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notion_page_id VARCHAR(255),
    summary TEXT NOT NULL
);

CREATE INDEX idx_dedupe_chat_key ON dedupe_entry (chat_id, dedupe_key);

CREATE TABLE user_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    default_remind_minutes INTEGER,
    default_timezone VARCHAR(128) NOT NULL,
    working_hours_start TIME,
    working_hours_end TIME,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_user_pref_chat_id ON user_preference (chat_id);

CREATE TABLE type_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    typical_duration_minutes INTEGER,
    default_location VARCHAR(255),
    default_remind_minutes INTEGER,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_type_pref_chat_type UNIQUE (chat_id, event_type)
);

CREATE INDEX idx_type_pref_chat_id ON type_preference (chat_id);

CREATE TABLE event_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    event_type VARCHAR(255),
    duration_minutes INTEGER,
    location VARCHAR(255),
    remind_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_event_stat_chat_id ON event_stat (chat_id);
CREATE INDEX idx_event_stat_chat_type ON event_stat (chat_id, event_type);
